dataset_configs:
  train:
    cdr_sequences_path: ./datasets/doggy_data/train_input
    fr_sequences_path: ./datasets/doggy_data/train_output
  val:
    cdr_sequences_path: ./datasets/doggy_data/train_input
    fr_sequences_path: ./datasets/doggy_data/train_output
  test:
    cdr_sequences_path: ./datasets/doggy_data/train_input
    fr_sequences_path: ./datasets/doggy_data/train_output
model_configs:
  model_type: DoggyTransformer
  tokenizer: Base
  hyperparameters:
    max_seq_len: 400
    hidden_dim: 64
    nhead: 4
    num_layers: 1
    regularizers: []
    dropout: 0.5
    batch_size: 32
    optimizer: "adam"
    learning_rate: 1e-4
    grad_accumulation_step: 1
    immunogenicity_as_value: False
training_configs:
  epochs: 100
  eval_steps: 1
  checkpoint_steps: 10
  device: 0
  random_seed: 1234
  outputs_dir: "train_outputs"
